version: '3'  
services:  
  node-web:  
    container_name: TuoLuoAdmin
    image: tuoluonode
    build:  
      context: .  
      dockerfile: Dockerfile  
    ports:  
      - "3000:3000"  
    volumes:  
      - .:/app  
      - /app/node_modules
    working_dir: /app  
    command: ["node","./index.js"]