version: "3.3"
services:
  # mysql 容器
  mysql_tuoluojiang:
    container_name: mysql_tuoluojiang #指定容器名
#    image: daocloud.io/library/mysql:5.7.5-m15 #M1芯片可以采用这个镜像
    image: mysql:8.0 #一般电脑可以用这个镜像
    ports:
      - 3376:3306
    # 环境变量
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'tuoluojiang'
    privileged: true
    command:
       --character-set-server=utf8mb4
       --collation-server=utf8mb4_general_ci
       --explicit_defaults_for_timestamp=true
       --lower_case_table_names=1
       --max_allowed_packet=128M
       --default-authentication-plugin=mysql_native_password
       --sql-mode="NO_ENGINE_SUBSTITUTION"
    working_dir: /var/lib/mysql
    volumes:
      - ./helper/docker-compose/mysql/my.cnf:/etc/mysql/my.cnf
      - ./helper/docker-compose/mysql/data:/var/lib/mysql #挂载数据目录到本地
      - ./helper/docker-compose/mysql/log:/var/log/mysql
    networks:
      app_net:
        # 固定子网ip，网段必须在子网络192.168.*.*
        ipv4_address: 192.168.10.14
  # redis 容器
  redis_tuoluojiang:
    container_name: redis_tuoluojiang
    image: 'redis:latest'
    ports:
      - "6389:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./helper/docker-compose/redis/data:/data #挂载数据目录到本地
      - ./helper/docker-compose/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      app_net:
        ipv4_address: 192.168.10.15
  # php 容器
  tuoluojiang:
    container_name: tuoluojiang #指定容器名
    image: tuoluojiang #指定镜像名
    build:
      context: ./helper/docker-compose/php #dockerfile文件路径
      dockerfile: Dockerfile #制定dockerfile文件名称
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - 20300:20200
    tmpfs: /var/temp #上传临时文件夹
    working_dir: /var/www
    volumes:
      - ./:/var/www #程序运行目录
      - ./storage:/var/www/temp #程序缓存目录
      - ./helper/docker-compose/php/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini
    command:
      php ./bin/laravels restart
    networks:
      app_net:
        ipv4_address: 192.168.10.16
networks: #网络配置
  app_net: #网络名称
    driver: bridge
    ipam: #网络配置
      driver: default
      config:
        - subnet: 192.168.10.0/24 #IP区间

